### ISSUE TITLE
pool_pump.next_run_schedule and pool_pump.total_daily_filtering_duration don't keep the customization

### ISSUE THREAD

**Issue by dadge** [oncleben31/ha-pool_pump#13]
## Version of the custom_component
Branch dev

## Configuration

`homeassistant:
  customize: !include customize.yaml`

`pool_pump.total_daily_filtering_duration:
  friendly_name: Temps de filtration
  icon: mdi:progress-clock
  unit_of_measurement: h
pool_pump.next_run_schedule:
  friendly_name: Prochain Cycle
  icon: mdi:calendar-arrow-right`

## Describe the bug
Hello, 
I tried to update the customization for your automatic created entities to be able to display it in a fancy way in my dashboard, but for a reason I don't understand, the customizations disappear after a while or a after a restart.

![image](https://user-images.githubusercontent.com/1717155/115870772-02fe1400-a440-11eb-842d-b14ed0a81213.png)

I tried to reload the core config from the UI or call the service homeassistant.reload_core_config with the idea to add this call in the code at the end of check function, but it doesn't seems to work. 

Do you have any idea how to make my customizations permanent or reload them ? 

Anyways congrats for your work, this component is great, I used to deals this pump filtering schedule with an automation (4 cycles, with duration for each = temperature/8, starting at the sunrise, with a break of 2 hrs between each cycle) but your stuff make it even simpler.

Beau boulot! 👍

**Comment by dadge** [comment]
Ok I resolved my issue by 'encapsulating' your variables with my own input number and text, the sync is made with automations. 
This ways it keeps separate 'private' technical data (your entity) and 'public' ones (exposed to the public)
The result meets my expectations :
![image](https://user-images.githubusercontent.com/1717155/115887047-d3f09e00-a451-11eb-9488-ac2ff2e70863.png)
 and I increased my yaml/ha skills !

Here is my code for the one interested. 

```yaml
input_number:
  total_daily_filtering_duration:
    name: Temps de filtration
    min: 0
    max: 24
    step: 0.1
    unit_of_measurement: h
    icon: mdi:progress-clock


input_text:
  next_run_schedule:
    name: Prochain Cycle
    icon: mdi:calendar-arrow-right

automation:
  - alias: Set total daily filtering duration
    trigger:
      - platform: state
        entity_id: pool_pump.total_daily_filtering_duration
    action:
      - service: input_number.set_value
        target:
          entity_id: input_number.total_daily_filtering_duration
        data:
          value: '{{ trigger.to_state.state }}'
    mode: single
  - alias: Set next run schedule
    description: ''
    trigger:
      - platform: state
        entity_id: pool_pump.next_run_schedule
    condition: []
    action:
      - service: input_text.set_value
        target:
          entity_id: input_text.next_run_schedule
        data:
          value: '{{ trigger.to_state.state }}'
    mode: single
```

Thanks, I'll continue to provide you feedback.
