### ISSUE TITLE
Bug for Filtration time, impossible to use more than ~17h

### ISSUE THREAD

**Issue by roumano** [oncleben31/ha-pool_pump#32]
## Version of the custom_component
i'm using the dev version of this extension

## Configuration

```yaml

pool_pump:
  switch_entity_id: switch.pompe_piscine
  pool_pump_mode_entity_id: input_select.pool_pump_mode
  pool_temperature_entity_id: sensor.piscine_filtrage
  schedule_break_in_hours: 0.0
```

## Describe the bug
it's impossible to filter more than around 17-18 hours due to pivot attribute and 1/3 before, 2/3 after.
as example value, today : 
- The pool temperature is 28°C
- Pool_pump calculate a need of 18h26 of filtration
- The pivot is define automaticaly to 13h42
- "only" 1/3 of 18h26 was made on the morning (before the pivot)
- So pool pump is planned to filter from 13h43 to 02h00 this afternoon

But at midnight, the pool_pump calculate a new filtration need as it's a new day and the `automation every 15minutes of pool_pump` stop the filtration

So today it will be filtering around **16h26** instead of **18h26 expected**

For me, it's a important bug as it can result important consequence on the water due to lack of filtration when it's very hot.
