### ISSUE TITLE
Erreur temperature

### ISSUE THREAD

**Issue by mycanaletto** [oncleben31/ha-pool_pump#9]
Bonjour,

Le composant est installé mais j'ai cette erreur, il y a un truc qui m'échappe : 
_Invalid config for [pool_pump]: [pool_temperature_entity_id] is an invalid option for [pool_pump]. Check: pool_pump->pool_pump->pool_temperature_entity_id. (See /config/configuration.yaml, line 69)._ 

Ma sonde est OK et remonte bien la temp. 

```
pool_pump:
  switch_entity_id: switch.sonoff_102ac98_4
  pool_pump_mode_entity_id: input_select.pool_pump_mode
  pool_temperature_entity_id: sensor.sonoff_102c7845_temperature
```
Et si je ne mets aucune option l'erreur fait référence à des options pon documentées mais pas la température...
_Invalid config for [pool_pump]: required key not provided @ data['pool_pump']['pool_pump_mode_entity_id']. Got None
required key not provided @ data['pool_pump']['run_pool_pump_hours_off_season_entity_id']. Got None
required key not provided @ data['pool_pump']['run_pool_pump_hours_swimming_season_entity_id']. Got None
required key not provided @ data['pool_pump']['swimming_season_entity_id']. Got None
required key not provided @ data['pool_pump']['switch_entity_id']. Got None. (See ?, line ?)._
